### ISSUE TITLE
[Question] BiphasicAxonMapModel paper-code discrepancy

### ISSUE THREAD

**Issue by ju-w** [pulse2percept/pulse2percept#575] opened 2023-11-01 15:36 UTC
Hi,

equation 3 of the paper reads

$$
a^{tilde} (t) = (A_0t + A_1)^{−1}a
$$

so does the comment 
https://github.com/pulse2percept/pulse2percept/blob/202fac944c9f361b3633d39a8bf5a6680ac4dca7/pulse2percept/models/granley2021.py#L51

however, in the actual implementation, the scaling it is _multiplication_ instead of _division_

https://github.com/pulse2percept/pulse2percept/blob/202fac944c9f361b3633d39a8bf5a6680ac4dca7/pulse2percept/models/granley2021.py#L76
https://github.com/pulse2percept/pulse2percept/blob/202fac944c9f361b3633d39a8bf5a6680ac4dca7/pulse2percept/models/granley2021.py#L90

**Comment by jgranley** [comment] 2023-11-02 00:52
Hi, thanks for the question. 

This is actually by design, and the code (not the paper) is the more correct version. This is poorly documented in the current code, which I will update.

The paper originally modulated the threshold amplitude as pulse duration was modulating using Eq 3, fit to data from Weitz et al 2015, Figure 1. However, the thresholds plotted in that figure were in terms of charge density, not amplitude, which was not noticed before the paper was published at EMBC. 

Since then the equation has been slightly modified, and was refit to better data from Horsager et al. 2009, resulting in the version currently in pulse2percept. I am currently looking into if it's possible to update the paper to include this information, but it is not clear how to upload errata for this conference. 

If you want the exact version in the original paper, you can check see the papers original accompanying [repository](https://github.com/bionicvisionlab/2021-BiphasicAxonMap/tree/master). But I would recommend using the version currently in pulse2percept, which lines up with argus II patient outcomes much better:
![image](https://github.com/pulse2percept/pulse2percept/assets/25232557/726a5bb4-ac10-4e37-8d86-bb70b5d1624b)

**Comment by jgranley** [comment] 2023-11-02 00:53
I'm going to merge a branch which corrects the docstrings, and points out the change in equation, and then close the issue. Feel free to reopen if you have any further questions

**Closed** 2023-11-02 02:19 UTC
Labels: bug
